2025-09-28 03:18:23,552 15356 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-28 03:18:23,560 15356 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-28 03:18:23,577 15356 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-28 03:18:23,688 15356 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-28 03:18:23,805 15356 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-28 03:18:23,827 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-28 03:18:23,905 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-28 03:18:23,914 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-28 03:18:23,945 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-28 03:18:23,978 15356 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-28 03:18:23,978 15356 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:23,978 15356 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:23,978 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:18:23] "GET /websocket?version=17.0-1 HTTP/1.1" 500 - 191 0.056 0.386
2025-09-28 03:18:24,452 15356 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-28 03:18:24,461 15356 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-28 03:18:24,479 15356 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-28 03:18:24,518 15356 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-28 03:18:24,661 15356 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-28 03:18:24,686 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-28 03:18:24,766 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-28 03:18:24,784 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-28 03:18:24,833 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-28 03:18:24,859 15356 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-28 03:18:24,859 15356 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:24,859 15356 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:24,868 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:18:24] "GET /web HTTP/1.1" 500 - 191 0.107 0.322
2025-09-28 03:18:24,941 15356 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-28 03:18:24,950 15356 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-28 03:18:24,964 15356 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-28 03:18:24,995 15356 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-28 03:18:25,108 15356 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-28 03:18:25,133 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-28 03:18:25,256 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-28 03:18:25,273 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-28 03:18:25,321 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-28 03:18:25,355 15356 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-28 03:18:25,355 15356 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:25,355 15356 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:25,365 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:18:25] "GET /favicon.ico HTTP/1.1" 500 - 191 0.128 0.305
2025-09-28 03:18:26,482 15356 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-28 03:18:26,489 15356 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-28 03:18:26,497 15356 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-28 03:18:26,531 15356 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-28 03:18:26,660 15356 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-28 03:18:26,677 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-28 03:18:26,746 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-28 03:18:26,755 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-28 03:18:26,783 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-28 03:18:26,805 15356 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-28 03:18:26,805 15356 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:26,809 15356 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 87, in __new__
    return cls.registries[db_name]
           ~~~~~~~~~~~~~~^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\lru.py", line 34, in __getitem__
    a = self.d[obj]
        ~~~~~~^^^^^
KeyError: 'ssi_odoo_demo'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 464, in _tag_record
    record = model._load_records([data], self.mode == 'update')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5093, in _load_records
    data['record']._load_records_write(data['values'])
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5024, in _load_records_write
    self.write(values)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 4387, in write
    raise ValueError("Invalid field %r on model %r" % (fname, self._name))
ValueError: Invalid field 'active_on_startup' on model 'geoengine.raster.layer'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 577, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/views/customer_map_geoengine_views.xml:97, somewhere inside
<record id="customer_map_raster_osm_detailed" model="geoengine.raster.layer">
            <field name="name">OpenStreetMap</field>
            <field name="raster_type">osm</field>
            <field name="view_id" ref="view_customer_map_geoengine"/>
            <field name="overlay" eval="False"/>
            <field name="sequence">1</field>
            <field name="active_on_startup" eval="True"/>
        </record>
2025-09-28 03:18:26,809 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:18:26] "GET /web/service-worker.js HTTP/1.1" 500 - 191 0.041 0.292
2025-09-28 03:19:16,155 15356 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-28 03:19:16,170 15356 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-28 03:19:16,188 15356 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-28 03:19:16,227 15356 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-28 03:19:16,355 15356 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-28 03:19:16,396 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-28 03:19:16,578 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-28 03:19:16,595 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-28 03:19:16,655 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-28 03:19:16,710 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-28 03:19:16,723 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-28 03:19:16,773 15356 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-28 03:19:17,371 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: maximum recursion depth exceeded 
2025-09-28 03:19:17,914 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:17,914 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-28 03:19:17,914 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:18,605 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:18,605 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:19,155 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:19,155 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:19,695 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:19,695 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:20,261 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:20,261 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:20,841 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:20,841 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:21,451 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:21,452 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:21,916 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:21,916 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:22,298 15356 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded in comparison 
2025-09-28 03:19:22,298 15356 WARNING ? odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:19:22,397 15356 INFO ? odoo.modules.loading: Module customer_map_tracking loaded in 6.17s, 5077 queries (+5077 other) 
2025-09-28 03:19:23,442 15356 WARNING ? odoo.api.create: The model odoo.addons.product_master.models.product_template is not overriding the create method in batch 
2025-09-28 03:19:23,459 15356 WARNING ? odoo.api.create: The model odoo.addons.purchase_fsm_assignment_api.models.installation_checklist is not overriding the create method in batch 
2025-09-28 03:19:23,513 15356 INFO ? odoo.modules.loading: 77 modules loaded in 7.33s, 5077 queries (+5077 extra) 
2025-09-28 03:19:23,642 15356 WARNING ? py.warnings: D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py:536: UserWarning: Property fsm.size.name.required should be a boolean (True).
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1002, in _bootstrap
    self._bootstrap_inner()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 361, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 127, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\socketserver.py", line 755, in __init__
    self.handle()
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\werkzeug\serving.py", line 363, in handle
    super().handle()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python311\Lib\http\server.py", line 424, in handle_one_request
    method()
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\werkzeug\serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\werkzeug\serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 507, in load_modules
    registry.setup_models(cr)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 319, in setup_models
    model._setup_fields()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 3420, in _setup_fields
    field.setup(self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py", line 536, in setup
    warnings.warn(f'Property {self}.required should be a boolean ({self.required}).')
 
2025-09-28 03:19:23,955 15356 INFO ? odoo.modules.registry: verifying fields for every extended model 
2025-09-28 03:19:23,977 15356 INFO ? odoo.modules.loading: Modules loaded. 
2025-09-28 03:19:23,983 15356 INFO ? odoo.modules.registry: Registry loaded in 7.843s 
2025-09-28 03:19:23,992 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-28 03:19:24,312 15356 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-28 03:19:24,835 15356 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 180. Replace by @t-out 
2025-09-28 03:19:24,835 15356 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 180. Replace by @t-out 
2025-09-28 03:19:24,841 15356 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 180. Replace by @t-out 
2025-09-28 03:19:24,845 15356 INFO ssi_odoo_demo odoo.modules.registry: Caches invalidated, signaling through the database: ['default', 'templates'] 
2025-09-28 03:19:24,895 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:24] "GET /web HTTP/1.1" 200 - 5550 2.752 6.002
2025-09-28 03:19:25,227 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "GET /bus/websocket_worker_bundle?v=17.0-1 HTTP/1.1" 304 - 4 0.001 0.017
2025-09-28 03:19:25,477 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "POST /web/action/load HTTP/1.1" 200 - 10 0.008 0.263
2025-09-28 03:19:25,552 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "GET /bus/websocket_worker_bundle?v=17.0-1 HTTP/1.1" 200 - 4 0.015 0.001
2025-09-28 03:19:25,677 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "POST /mail/init_messaging HTTP/1.1" 200 - 37 0.064 0.057
2025-09-28 03:19:25,696 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.1" 200 - 6 0.010 0.070
2025-09-28 03:19:25,773 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 26 0.049 0.038
2025-09-28 03:19:25,779 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "POST /mail/load_message_failures HTTP/1.1" 200 - 3 0.005 0.053
2025-09-28 03:19:25,779 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 1 0.005 0.051
2025-09-28 03:19:25,822 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.016 0.002
2025-09-28 03:19:25,855 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:25] "GET /base_geoengine/static/lib/ol-7.2.2/ol.js HTTP/1.1" 200 - 0 0.000 0.006
2025-09-28 03:19:26,023 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "POST /web/dataset/call_kw/geoengine.vector.layer/fields_get HTTP/1.1" 200 - 8 0.014 0.010
2025-09-28 03:19:26,101 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.000 0.006
2025-09-28 03:19:26,105 15356 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-09-28 03:19:26,187 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "POST /web/dataset/call_kw/geoengine.vector.layer/get_views HTTP/1.1" 200 - 7 0.005 0.030
2025-09-28 03:19:26,191 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 8 0.026 0.012
2025-09-28 03:19:26,349 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 10 0.005 0.013
2025-09-28 03:19:26,520 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.003 0.015
2025-09-28 03:19:26,691 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.006 0.011
2025-09-28 03:19:26,706 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:26] "GET /web/image?model=res.users&field=avatar_128&id=1 HTTP/1.1" 304 - 7 0.001 0.014
2025-09-28 03:19:28,642 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:28] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.000 0.009
2025-09-28 03:19:28,841 15356 INFO ssi_odoo_demo odoo.addons.base.models.assetsbundle: Generating a new asset bundle attachment /web/assets/5a1cab6/web.assets_web.min.js (id:529) 
2025-09-28 03:19:28,845 15356 INFO ssi_odoo_demo odoo.addons.base.models.assetsbundle: Deleting attachments [528] (matching /web/assets/_______/web.assets_web.min.js) because it was replaced with /web/assets/5a1cab6/web.assets_web.min.js 
2025-09-28 03:19:29,458 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:29] "GET /base_geoengine/static/lib/chromajs-2.4.2/chroma.js HTTP/1.1" 200 - 0 0.000 0.002
2025-09-28 03:19:29,458 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:29] "GET /base_geoengine/static/lib/geostats-2.0.0/geostats.js HTTP/1.1" 200 - 0 0.000 0.002
2025-09-28 03:19:29,469 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:29] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.000 0.004
2025-09-28 03:19:29,855 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:19:29] "GET /web/assets/5a1cab6/web.assets_web.min.js HTTP/1.1" 200 - 30 0.056 4.515
2025-09-28 03:20:01,464 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:01] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.000 0.008
2025-09-28 03:20:01,809 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:01] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.007 0.017
2025-09-28 03:20:02,059 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:02] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.005 0.022
2025-09-28 03:20:02,138 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:02] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.000 0.007
2025-09-28 03:20:12,115 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:12] "POST /web/action/load HTTP/1.1" 200 - 10 0.008 0.015
2025-09-28 03:20:12,505 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:12] "POST /web/dataset/call_kw/geoengine.raster.layer/get_views HTTP/1.1" 200 - 10 0.005 0.066
2025-09-28 03:20:12,695 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:12] "POST /web/dataset/call_kw/geoengine.raster.layer/web_read HTTP/1.1" 200 - 3 0.000 0.011
2025-09-28 03:20:28,785 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:28] "POST /web/dataset/call_kw/ir.ui.view/name_search HTTP/1.1" 200 - 2 0.010 0.010
2025-09-28 03:20:38,559 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:38] "POST /web/dataset/call_kw/geoengine.raster.layer/web_save HTTP/1.1" 200 - 3 0.004 0.005
2025-09-28 03:20:51,433 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:51] "POST /web/action/load HTTP/1.1" 200 - 9 0.001 0.028
2025-09-28 03:20:51,760 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:51] "POST /web/dataset/call_kw/geoengine.raster.layer/web_read HTTP/1.1" 200 - 3 0.009 0.000
2025-09-28 03:20:54,279 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:54] "POST /web/dataset/call_kw/ir.ui.view/name_search HTTP/1.1" 200 - 2 0.000 0.009
2025-09-28 03:20:57,315 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:57] "POST /web/dataset/call_kw/geoengine.raster.layer/web_save HTTP/1.1" 200 - 3 0.003 0.044
2025-09-28 03:20:59,265 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:59] "POST /web/action/load HTTP/1.1" 200 - 10 0.006 0.016
2025-09-28 03:20:59,608 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:59] "POST /web/dataset/call_kw/geoengine.vector.layer/get_views HTTP/1.1" 200 - 4 0.003 0.020
2025-09-28 03:20:59,863 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:59] "POST /web/dataset/call_kw/geoengine.vector.layer/web_read HTTP/1.1" 200 - 4 0.000 0.015
2025-09-28 03:20:59,949 15356 INFO ? werkzeug: 127.0.0.1 - - [28/Sep/2025 03:20:59] "GET /web/static/img/transparent.png HTTP/1.1" 200 - 0 0.000 0.020
2025-09-28 03:21:13,848 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2025-09-28 03:21:13,934 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_attachment: filestore gc 2 checked, 1 removed 
2025-09-28 03:21:14,007 15356 INFO ssi_odoo_demo odoo.addons.base.models.res_users: GC'd 0 user log entries 
2025-09-28 03:21:14,055 15356 INFO ssi_odoo_demo odoo.addons.auth_totp.models.auth_totp: GC'd 0 totp devices entries 
2025-09-28 03:21:14,084 15356 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted bus.bus records with IDs: [302, 303, 304, 305] 
2025-09-28 03:21:14,255 15356 INFO ssi_odoo_demo odoo.addons.sms.models.sms_sms: GC'd 0 sms marked for deletion 
2025-09-28 03:21:14,473 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Auto-vacuum internal data` (0.625s). 
2025-09-28 03:21:17,300 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:17] "POST /web/dataset/call_kw/geoengine.vector.layer/web_save HTTP/1.1" 200 - 3 0.002 0.026
2025-09-28 03:21:17,635 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:17] "POST /web/dataset/call_kw/geoengine.vector.layer/set_field_real_name HTTP/1.1" 200 - 2 0.003 0.009
2025-09-28 03:21:17,888 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:17] "POST /web/dataset/call_kw/geoengine.vector.layer/set_field_real_name HTTP/1.1" 200 - 1 0.000 0.007
2025-09-28 03:21:46,395 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:46] "POST /web/action/load HTTP/1.1" 200 - 9 0.003 0.026
2025-09-28 03:21:46,793 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:46] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 13 0.022 0.041
2025-09-28 03:21:47,005 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:47] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.008 0.000
2025-09-28 03:21:47,130 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:47] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.000 0.000
2025-09-28 03:21:49,080 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:49] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.000 0.009
2025-09-28 03:21:49,485 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:49] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.023 0.017
2025-09-28 03:21:49,547 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:49] "POST /mail/thread/messages HTTP/1.1" 200 - 19 0.045 0.023
2025-09-28 03:21:51,912 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:51] "POST /web/dataset/call_button HTTP/1.1" 200 - 1 0.001 0.005
2025-09-28 03:21:52,291 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:52] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 10 0.011 0.034
2025-09-28 03:21:52,519 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:52] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.007 0.006
2025-09-28 03:21:52,636 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:52] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.009 0.017
2025-09-28 03:21:52,855 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:52] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.000 0.009
2025-09-28 03:21:52,965 15356 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:21:52] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.003 0.006
2025-09-28 03:24:14,536 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2025-09-28 03:24:14,673 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_attachment: filestore gc 0 checked, 0 removed 
2025-09-28 03:24:14,832 15356 INFO ssi_odoo_demo odoo.addons.base.models.res_users: GC'd 0 user log entries 
2025-09-28 03:24:14,896 15356 INFO ssi_odoo_demo odoo.addons.auth_totp.models.auth_totp: GC'd 0 totp devices entries 
2025-09-28 03:24:15,241 15356 INFO ssi_odoo_demo odoo.addons.sms.models.sms_sms: GC'd 0 sms marked for deletion 
2025-09-28 03:24:15,604 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Auto-vacuum internal data` (1.063s). 
2025-09-28 03:24:15,627 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Users: Notify About Unregistered Users`. 
2025-09-28 03:24:15,647 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Users: Notify About Unregistered Users` (0.020s). 
2025-09-28 03:24:15,655 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `SMS: SMS Queue Manager`. 
2025-09-28 03:24:15,663 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `SMS: SMS Queue Manager` (0.008s). 
2025-09-28 03:24:15,679 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Partner Autocomplete: Sync with remote DB`. 
2025-09-28 03:24:15,679 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Partner Autocomplete: Sync with remote DB` (0.000s). 
2025-09-28 03:24:15,696 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Snailmail: process letters queue`. 
2025-09-28 03:24:15,705 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Snailmail: process letters queue` (0.010s). 
2025-09-28 03:24:15,721 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Notification: Send scheduled message notifications`. 
2025-09-28 03:24:15,727 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Notification: Send scheduled message notifications` (0.007s). 
2025-09-28 03:24:15,741 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Mail: Email Queue Manager`. 
2025-09-28 03:24:15,745 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Mail: Email Queue Manager` (0.005s). 
2025-09-28 03:24:15,759 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Portal Users Deletion`. 
2025-09-28 03:24:15,772 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Portal Users Deletion` (0.014s). 
2025-09-28 03:24:15,777 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Notification: Delete Notifications older than 6 Month`. 
2025-09-28 03:24:15,793 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Notification: Delete Notifications older than 6 Month` (0.016s). 
2025-09-28 03:24:15,805 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Discuss: channel member unmute`. 
2025-09-28 03:24:15,806 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Discuss: channel member unmute` (0.001s). 
2025-09-28 03:24:15,823 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Mail: send web push notification`. 
2025-09-28 03:24:15,827 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Mail: send web push notification` (0.004s). 
2025-09-28 03:28:24,077 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Send invoices automatically`. 
2025-09-28 03:28:24,105 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Send invoices automatically` (0.027s). 
2025-09-28 03:29:15,877 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Procurement: run scheduler`. 
2025-09-28 03:29:15,987 15356 INFO ssi_odoo_demo odoo.addons.stock.models.stock_rule: _run_scheduler_tasks is finished and committed 
2025-09-28 03:29:15,987 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Procurement: run scheduler` (0.105s). 
2025-09-28 03:29:16,003 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Purchase reminder`. 
2025-09-28 03:29:16,033 15356 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Purchase reminder` (0.029s). 
2025-09-28 03:46:07,021 15356 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-28 03:46:07,022 15356 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-28 03:46:07,304 15356 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
2025-09-28 03:46:11,773 10688 INFO ? odoo: Odoo version 17.0 
2025-09-28 03:46:11,773 10688 INFO ? odoo: Using configuration file at D:\work-project\ssi\odoo_demo\odoo\odoo.conf 
2025-09-28 03:46:11,773 10688 INFO ? odoo: addons paths: ['D:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\data\\addons\\17.0', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\field_service', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\geospatial', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons'] 
2025-09-28 03:46:11,777 10688 INFO ? odoo: database: odoo@localhost:5432 
2025-09-28 03:46:12,055 10688 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-28 03:46:12,500 10688 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-28 03:46:12,513 10688 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-28 03:46:12,573 10688 INFO ssi_odoo_demo odoo.modules.loading: loading 1 modules... 
2025-09-28 03:46:12,577 10688 INFO ssi_odoo_demo odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-28 03:46:12,609 10688 INFO ssi_odoo_demo odoo.modules.loading: updating modules list 
2025-09-28 03:46:12,614 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-28 03:46:14,270 10688 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-28 03:46:14,496 10688 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'stock_qr_tracking', defaulting to LGPL-3 
2025-09-28 03:46:14,892 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-28 03:46:14,892 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-28 03:46:16,095 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-28 03:46:16,155 10688 INFO ssi_odoo_demo odoo.modules.loading: loading 77 modules... 
2025-09-28 03:46:16,835 10688 INFO ssi_odoo_demo odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-28 03:46:16,916 10688 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.customer_map_tracking.models.customer_map is not overriding the create method in batch 
2025-09-28 03:46:16,967 10688 INFO ssi_odoo_demo odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-28 03:46:17,055 10688 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-28 03:46:17,184 10688 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-28 03:46:17,225 10688 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-28 03:46:17,295 10688 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-28 03:46:17,345 10688 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-28 03:46:17,359 10688 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-28 03:46:17,383 10688 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-28 03:46:18,177 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-28 03:46:18,177 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:19,177 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:19,177 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:20,224 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:20,224 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:21,225 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:21,225 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:22,227 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:22,227 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:23,345 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:23,345 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:24,375 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:24,377 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:25,443 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:25,445 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:26,457 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:26,457 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:27,477 10688 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 03:46:27,477 10688 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 03:46:27,627 10688 INFO ssi_odoo_demo odoo.modules.loading: Module customer_map_tracking loaded in 10.79s, 5128 queries (+5128 other) 
2025-09-28 03:46:29,772 10688 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.product_master.models.product_template is not overriding the create method in batch 
2025-09-28 03:46:29,796 10688 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.purchase_fsm_assignment_api.models.installation_checklist is not overriding the create method in batch 
2025-09-28 03:46:29,927 10688 INFO ssi_odoo_demo odoo.modules.loading: 77 modules loaded in 13.77s, 5128 queries (+5128 extra) 
2025-09-28 03:46:30,448 10688 WARNING ssi_odoo_demo py.warnings: D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py:536: UserWarning: Property fsm.size.name.required should be a boolean (True).
  File "D:\work-project\ssi\odoo_demo\odoo\odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\command.py", line 67, in main
    o.run(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 186, in run
    main(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 179, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1469, in start
    rc = server.run(preload, stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 635, in run
    rc = preload_registries(preload)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 493, in load_modules
    registry.setup_models(cr)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 319, in setup_models
    model._setup_fields()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 3420, in _setup_fields
    field.setup(self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py", line 536, in setup
    warnings.warn(f'Property {self}.required should be a boolean ({self.required}).')
 
2025-09-28 03:46:31,391 10688 INFO ssi_odoo_demo odoo.modules.registry: verifying fields for every extended model 
2025-09-28 03:46:32,741 10688 INFO ssi_odoo_demo odoo.modules.loading: Modules loaded. 
2025-09-28 03:46:32,763 10688 INFO ssi_odoo_demo odoo.modules.registry: Registry loaded in 20.263s 
2025-09-28 03:46:32,971 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-28 03:46:33,005 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-28 03:46:33,095 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:33] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 3 0.006 16.113
2025-09-28 03:46:33,473 10688 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-09-28 03:46:33,655 10688 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-28 03:46:35,246 10688 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 180. Replace by @t-out 
2025-09-28 03:46:35,246 10688 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 180. Replace by @t-out 
2025-09-28 03:46:35,246 10688 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 180. Replace by @t-out 
2025-09-28 03:46:35,261 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:35] "GET /web HTTP/1.1" 200 - 81 0.149 20.951
2025-09-28 03:46:35,485 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:35] "GET /bus/websocket_worker_bundle?v=17.0-1 HTTP/1.1" 304 - 4 0.002 0.011
2025-09-28 03:46:35,563 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:35] "POST /mail/init_messaging HTTP/1.1" 200 - 36 0.037 0.041
2025-09-28 03:46:35,895 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:35] "POST /mail/load_message_failures HTTP/1.1" 200 - 4 0.007 0.011
2025-09-28 03:46:35,947 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:35] "GET /web/image?model=res.users&field=avatar_128&id=1 HTTP/1.1" 304 - 7 0.012 0.030
2025-09-28 03:46:35,961 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:35] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 1 0.000 0.016
2025-09-28 03:46:36,409 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:36] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 8 0.039 0.094
2025-09-28 03:46:36,527 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:36] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.1" 200 - 6 0.000 0.692
2025-09-28 03:46:36,622 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:36] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 18 0.042 0.686
2025-09-28 03:46:36,958 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:36] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.004 0.004
2025-09-28 03:46:37,238 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:37] "POST /web/dataset/call_kw/geoengine.vector.layer/fields_get HTTP/1.1" 200 - 8 0.000 0.031
2025-09-28 03:46:37,295 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:37] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.005 0.004
2025-09-28 03:46:37,340 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:37] "POST /web/dataset/call_kw/geoengine.vector.layer/get_views HTTP/1.1" 200 - 7 0.013 0.040
2025-09-28 03:46:37,591 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:37] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 10 0.008 0.026
2025-09-28 03:46:37,691 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:37] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.006 0.027
2025-09-28 03:46:37,923 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:37] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.003 0.011
2025-09-28 03:46:37,957 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:37] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.000 0.012
2025-09-28 03:46:40,995 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:40] "POST /web/action/load HTTP/1.1" 200 - 9 0.005 0.027
2025-09-28 03:46:41,306 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:41] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 14 0.005 0.081
2025-09-28 03:46:41,328 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:41] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.000 0.002
2025-09-28 03:46:41,641 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:41] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.000 0.008
2025-09-28 03:46:42,543 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:42] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.001 0.012
2025-09-28 03:46:43,859 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:43] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.002 0.009
2025-09-28 03:46:44,145 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:44] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.035 0.003
2025-09-28 03:46:44,310 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:44] "POST /mail/thread/messages HTTP/1.1" 200 - 19 0.033 0.037
2025-09-28 03:46:47,536 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:47] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.002 0.029
2025-09-28 03:46:57,897 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:46:57] "POST /web/dataset/call_button HTTP/1.1" 200 - 1 0.000 0.009
2025-09-28 03:47:03,013 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:03] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.027 0.008
2025-09-28 03:47:11,835 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:11] "POST /web/action/load HTTP/1.1" 200 - 9 0.002 0.028
2025-09-28 03:47:12,149 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:12] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 17 0.019 0.077
2025-09-28 03:47:12,177 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:12] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.005 0.006
2025-09-28 03:47:12,507 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:12] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.008 0.027
2025-09-28 03:47:12,556 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:12] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.014 0.021
2025-09-28 03:47:12,841 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:12] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.006 0.008
2025-09-28 03:47:16,811 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:16] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.001 0.004
2025-09-28 03:47:17,982 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:17] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.003 0.016
2025-09-28 03:47:18,333 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:18] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.010 0.020
2025-09-28 03:47:18,591 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:18] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.000 0.034
2025-09-28 03:47:18,665 10688 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 03:47:18] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.000 0.004
2025-09-28 03:47:33,023 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2025-09-28 03:47:33,182 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_attachment: filestore gc 0 checked, 0 removed 
2025-09-28 03:47:33,355 10688 INFO ssi_odoo_demo odoo.addons.base.models.res_users: GC'd 0 user log entries 
2025-09-28 03:47:33,449 10688 INFO ssi_odoo_demo odoo.addons.auth_totp.models.auth_totp: GC'd 0 totp devices entries 
2025-09-28 03:47:33,778 10688 INFO ssi_odoo_demo odoo.addons.sms.models.sms_sms: GC'd 0 sms marked for deletion 
2025-09-28 03:47:34,078 10688 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Auto-vacuum internal data` (1.055s). 
2025-09-28 03:48:11,678 10688 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-28 03:48:11,678 10688 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-28 03:48:12,687 10688 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 5 connections  
