2025-09-27 13:29:16,467 4956 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-27 13:29:16,473 4956 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-27 13:29:16,481 4956 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-27 13:29:16,497 4956 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:29:16,592 4956 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:29:16,624 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:29:16,684 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:29:16,697 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:29:16,724 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:29:16,746 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:29:16,756 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:29:16,774 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:29:16,792 4956 ERROR ? odoo.sql_db: bad query: 
                UPDATE customer_map 
                SET shape = ST_SetSRID(ST_MakePoint(106.816666,  -6.2), 4326)
                WHERE id = 72
            
ERROR: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:29:16,792 4956 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:29:16,793 4956 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-27 13:29:16,794 4956 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:29:16,795 4956 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:29:16,797 4956 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:29:16] "GET / HTTP/1.1" 500 - 261 0.098 0.238
2025-09-27 13:29:16,841 4956 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-27 13:29:16,845 4956 INFO ? odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-27 13:29:16,860 4956 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-27 13:29:16,889 4956 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:29:17,024 4956 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:29:17,061 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:29:17,132 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:29:17,145 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:29:17,171 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:29:17,191 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:29:17,202 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:29:17,218 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:29:17,227 4956 ERROR ? odoo.sql_db: bad query: 
                UPDATE customer_map 
                SET shape = ST_SetSRID(ST_MakePoint(106.816666,  -6.2), 4326)
                WHERE id = 73
            
ERROR: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:29:17,227 4956 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:29:17,237 4956 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-27 13:29:17,237 4956 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:29:17,241 4956 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:29:17,245 4956 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:29:17] "GET /favicon.ico HTTP/1.1" 500 - 261 0.095 0.317
2025-09-27 13:29:20,283 4956 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-27 13:29:20,292 4956 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-27 13:29:20,299 4956 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-27 13:29:20,323 4956 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:29:20,409 4956 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:29:20,441 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:29:20,490 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:29:20,498 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:29:20,506 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:29:20,527 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:29:20,541 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:29:20,560 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:29:20,584 4956 ERROR ? odoo.sql_db: bad query: 
                UPDATE customer_map 
                SET shape = ST_SetSRID(ST_MakePoint(106.816666,  -6.2), 4326)
                WHERE id = 74
            
ERROR: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:29:20,584 4956 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:29:20,586 4956 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-27 13:29:20,587 4956 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:29:20,588 4956 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:29:20,589 4956 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:29:20] "GET /websocket?version=17.0-1 HTTP/1.1" 500 - 261 0.092 0.214
2025-09-27 13:30:21,375 4956 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-27 13:30:21,378 4956 INFO ? odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-27 13:30:21,393 4956 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-27 13:30:21,412 4956 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:30:21,529 4956 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:30:21,567 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:30:21,628 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:30:21,649 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:30:21,677 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:30:21,706 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:30:21,715 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:30:21,730 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:30:21,759 4956 ERROR ? odoo.sql_db: bad query: 
                UPDATE customer_map 
                SET shape = ST_SetSRID(ST_MakePoint(106.816666,  -6.2), 4326)
                WHERE id = 75
            
ERROR: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:30:21,759 4956 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:30:21,760 4956 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-27 13:30:21,760 4956 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:30:21,760 4956 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:30:21,760 4956 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:30:21] "GET /websocket?version=17.0-1 HTTP/1.1" 500 - 261 0.093 0.297
2025-09-27 13:31:22,431 4956 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-27 13:31:22,438 4956 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-27 13:31:22,445 4956 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-27 13:31:22,455 4956 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:31:22,621 4956 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:31:22,656 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:31:22,727 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:31:22,741 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:31:22,769 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:31:22,795 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:31:22,803 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:31:22,823 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:31:22,841 4956 ERROR ? odoo.sql_db: bad query: 
                UPDATE customer_map 
                SET shape = ST_SetSRID(ST_MakePoint(106.816666,  -6.2), 4326)
                WHERE id = 76
            
ERROR: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:31:22,841 4956 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:31:22,841 4956 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-27 13:31:22,841 4956 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:31:22,845 4956 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:31:22,845 4956 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:31:22] "GET /websocket?version=17.0-1 HTTP/1.1" 500 - 261 0.103 0.318
2025-09-27 13:32:23,506 4956 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-27 13:32:23,506 4956 INFO ? odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-27 13:32:23,523 4956 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-27 13:32:23,541 4956 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:32:23,627 4956 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:32:23,655 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:32:23,741 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:32:23,753 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:32:23,775 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:32:23,793 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:32:23,800 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:32:23,819 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:32:23,838 4956 ERROR ? odoo.sql_db: bad query: 
                UPDATE customer_map 
                SET shape = ST_SetSRID(ST_MakePoint(106.816666,  -6.2), 4326)
                WHERE id = 77
            
ERROR: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:32:23,838 4956 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:32:23,840 4956 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-27 13:32:23,840 4956 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:32:23,840 4956 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:32:23,842 4956 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:32:23] "GET /websocket?version=17.0-1 HTTP/1.1" 500 - 261 0.085 0.254
2025-09-27 13:33:24,291 4956 INFO ? odoo.modules.loading: loading 1 modules... 
2025-09-27 13:33:24,299 4956 INFO ? odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-27 13:33:24,305 4956 INFO ? odoo.modules.loading: loading 77 modules... 
2025-09-27 13:33:24,314 4956 INFO ? odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:33:24,377 4956 INFO ? odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:33:24,377 4956 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-27 13:33:24,377 4956 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-27 13:33:24,409 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:33:24,471 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:33:24,481 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:33:24,505 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:33:24,527 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:33:24,527 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:33:24,553 4956 INFO ? odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:33:24,565 4956 ERROR ? odoo.sql_db: bad query: 
                UPDATE customer_map 
                SET shape = ST_SetSRID(ST_MakePoint(106.816666,  -6.2), 4326)
                WHERE id = 78
            
ERROR: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:33:24,565 4956 ERROR ? odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: Geometry SRID (4326) does not match column SRID (3857)
 
2025-09-27 13:33:24,565 4956 WARNING ? odoo.modules.loading: Transient module states were reset 
2025-09-27 13:33:24,565 4956 ERROR ? odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:33:24,574 4956 ERROR ? odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1949, in _serve_db
    self.registry = Registry(self.db).check_signaling()
                    ^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 89, in __new__
    return cls.new(db_name)
           ^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 481, in load_modules
    processed_modules += load_marked_modules(env, graph,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
                        ^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 229, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 73, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 635, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 621, in parse
    self._tag_root(de)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 564, in _tag_root
    f(rec)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\convert.py", line 575, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
odoo.tools.convert.ParseError: while parsing file:/d:/work-project/ssi/odoo_demo/odoo/custom_addons/customer_map_tracking/demo/customer_map_demo.xml:4
Failed to create PostGIS geometry. Please check your PostGIS installation.

View error context:
'-no context-'

2025-09-27 13:33:24,577 4956 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:24] "GET /websocket?version=17.0-1 HTTP/1.1" 500 - 261 0.104 0.190
2025-09-27 13:33:24,796 4956 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
2025-09-27 13:33:28,923 17888 INFO ? odoo: Odoo version 17.0 
2025-09-27 13:33:28,923 17888 INFO ? odoo: Using configuration file at D:\work-project\ssi\odoo_demo\odoo\odoo.conf 
2025-09-27 13:33:28,923 17888 INFO ? odoo: addons paths: ['D:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\data\\addons\\17.0', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\field_service', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\geospatial', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons'] 
2025-09-27 13:33:28,923 17888 INFO ? odoo: database: odoo@localhost:5432 
2025-09-27 13:33:29,148 17888 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-27 13:33:29,477 17888 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-27 13:33:29,487 17888 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-27 13:33:29,527 17888 INFO ssi_odoo_demo odoo.modules.loading: loading 1 modules... 
2025-09-27 13:33:29,536 17888 INFO ssi_odoo_demo odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-27 13:33:29,551 17888 INFO ssi_odoo_demo odoo.modules.loading: updating modules list 
2025-09-27 13:33:29,555 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-27 13:33:30,646 17888 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 13:33:30,777 17888 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'stock_qr_tracking', defaulting to LGPL-3 
2025-09-27 13:33:30,987 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 13:33:30,987 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 13:33:31,707 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-27 13:33:31,741 17888 INFO ssi_odoo_demo odoo.modules.loading: loading 77 modules... 
2025-09-27 13:33:32,477 17888 INFO ssi_odoo_demo odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:33:32,527 17888 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.customer_map_tracking.models.customer_map is not overriding the create method in batch 
2025-09-27 13:33:32,555 17888 INFO ssi_odoo_demo odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:33:32,646 17888 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:33:32,718 17888 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:33:32,741 17888 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:33:32,772 17888 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:33:32,795 17888 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:33:32,805 17888 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:33:32,830 17888 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:33:33,129 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: maximum recursion depth exceeded 
2025-09-27 13:33:33,445 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:33,445 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-27 13:33:33,445 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-27 13:33:33,445 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:33,737 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:33,737 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:34,005 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:34,005 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:34,382 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:34,382 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:34,683 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:34,683 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:34,927 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:34,927 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:35,230 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:35,230 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:35,545 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:35,545 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:35,866 17888 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:33:35,866 17888 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:33:35,895 17888 INFO ssi_odoo_demo odoo.modules.loading: Module customer_map_tracking loaded in 3.42s, 5151 queries (+5151 other) 
2025-09-27 13:33:36,831 17888 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.product_master.models.product_template is not overriding the create method in batch 
2025-09-27 13:33:36,843 17888 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.purchase_fsm_assignment_api.models.installation_checklist is not overriding the create method in batch 
2025-09-27 13:33:36,903 17888 INFO ssi_odoo_demo odoo.modules.loading: 77 modules loaded in 5.16s, 5151 queries (+5151 extra) 
2025-09-27 13:33:37,077 17888 WARNING ssi_odoo_demo py.warnings: D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py:536: UserWarning: Property fsm.size.name.required should be a boolean (True).
  File "D:\work-project\ssi\odoo_demo\odoo\odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\command.py", line 67, in main
    o.run(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 186, in run
    main(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 179, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1469, in start
    rc = server.run(preload, stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 635, in run
    rc = preload_registries(preload)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 493, in load_modules
    registry.setup_models(cr)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 319, in setup_models
    model._setup_fields()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 3420, in _setup_fields
    field.setup(self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py", line 536, in setup
    warnings.warn(f'Property {self}.required should be a boolean ({self.required}).')
 
2025-09-27 13:33:37,420 17888 INFO ssi_odoo_demo odoo.modules.loading: Model customer.map.import.wizard is declared but cannot be loaded! (Perhaps a module was partially removed or renamed) 
2025-09-27 13:33:37,423 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 1561@ir.model.fields.selection (customer_map_tracking.selection__customer_map_import_wizard__delimiter__|) 
2025-09-27 13:33:37,460 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37995] 
2025-09-27 13:33:37,460 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields.selection records with IDs: [1561] 
2025-09-27 13:33:37,461 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 1560@ir.model.fields.selection (customer_map_tracking.selection__customer_map_import_wizard__delimiter__	) 
2025-09-27 13:33:37,468 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37994] 
2025-09-27 13:33:37,468 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields.selection records with IDs: [1560] 
2025-09-27 13:33:37,469 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 1559@ir.model.fields.selection (customer_map_tracking.selection__customer_map_import_wizard__delimiter__;) 
2025-09-27 13:33:37,478 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37993] 
2025-09-27 13:33:37,478 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields.selection records with IDs: [1559] 
2025-09-27 13:33:37,480 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 1558@ir.model.fields.selection (customer_map_tracking.selection__customer_map_import_wizard__delimiter__,) 
2025-09-27 13:33:37,490 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37992] 
2025-09-27 13:33:37,490 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields.selection records with IDs: [1558] 
2025-09-27 13:33:37,491 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9325@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__write_date) 
2025-09-27 13:33:37,538 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37991] 
2025-09-27 13:33:37,538 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9325] 
2025-09-27 13:33:37,539 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9324@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__write_uid) 
2025-09-27 13:33:37,573 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37990] 
2025-09-27 13:33:37,573 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9324] 
2025-09-27 13:33:37,573 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9323@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__create_date) 
2025-09-27 13:33:37,602 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37989] 
2025-09-27 13:33:37,602 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9323] 
2025-09-27 13:33:37,603 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9322@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__create_uid) 
2025-09-27 13:33:37,629 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37988] 
2025-09-27 13:33:37,629 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9322] 
2025-09-27 13:33:37,629 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9321@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__display_name) 
2025-09-27 13:33:37,655 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37987] 
2025-09-27 13:33:37,655 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9321] 
2025-09-27 13:33:37,655 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9320@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__id) 
2025-09-27 13:33:37,695 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37986] 
2025-09-27 13:33:37,695 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9320] 
2025-09-27 13:33:37,695 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9319@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__import_summary) 
2025-09-27 13:33:37,723 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37985] 
2025-09-27 13:33:37,723 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9319] 
2025-09-27 13:33:37,723 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9318@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__preview_data) 
2025-09-27 13:33:37,758 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37984] 
2025-09-27 13:33:37,758 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9318] 
2025-09-27 13:33:37,758 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9317@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__update_existing) 
2025-09-27 13:33:37,792 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37983] 
2025-09-27 13:33:37,792 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9317] 
2025-09-27 13:33:37,793 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9316@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__has_header) 
2025-09-27 13:33:37,877 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37982] 
2025-09-27 13:33:37,877 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9316] 
2025-09-27 13:33:37,877 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9315@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__delimiter) 
2025-09-27 13:33:37,913 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37981] 
2025-09-27 13:33:37,913 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9315] 
2025-09-27 13:33:37,914 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9314@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__filename) 
2025-09-27 13:33:37,946 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37980] 
2025-09-27 13:33:37,946 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9314] 
2025-09-27 13:33:37,947 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9313@ir.model.fields (customer_map_tracking.field_customer_map_import_wizard__file_data) 
2025-09-27 13:33:37,976 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37979] 
2025-09-27 13:33:37,976 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9313] 
2025-09-27 13:33:37,976 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 9311@ir.model.fields (customer_map_tracking.field_customer_map__location_picker) 
2025-09-27 13:33:38,010 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37977] 
2025-09-27 13:33:38,010 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.fields records with IDs: [9311] 
2025-09-27 13:33:38,011 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 687@ir.model (customer_map_tracking.model_customer_map_import_wizard) 
2025-09-27 13:33:38,027 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: The model customer.map.import.wizard could not be dropped because it did not exist in the registry. 
2025-09-27 13:33:38,074 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [37963] 
2025-09-27 13:33:38,074 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model records with IDs: [687] 
2025-09-27 13:33:38,075 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 363@ir.ui.menu (customer_map_tracking.menu_customer_map) 
2025-09-27 13:33:38,084 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [36578] 
2025-09-27 13:33:38,084 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.ui.menu records with IDs: [363] 
2025-09-27 13:33:38,091 17888 INFO ssi_odoo_demo odoo.modules.registry: verifying fields for every extended model 
2025-09-27 13:33:38,776 17888 INFO ssi_odoo_demo odoo.modules.loading: Modules loaded. 
2025-09-27 13:33:38,779 17888 INFO ssi_odoo_demo odoo.modules.registry: Registry loaded in 9.302s 
2025-09-27 13:33:38,847 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-27 13:33:38,855 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:38] "GET / HTTP/1.1" 303 - 6 0.001 1.070
2025-09-27 13:33:39,116 17888 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 13:33:39,509 17888 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 180. Replace by @t-out 
2025-09-27 13:33:39,510 17888 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 180. Replace by @t-out 
2025-09-27 13:33:39,510 17888 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 180. Replace by @t-out 
2025-09-27 13:33:39,515 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:39] "GET /web HTTP/1.1" 200 - 78 0.066 0.573
2025-09-27 13:33:39,674 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:39] "GET /web/webclient/load_menus/4121c434c00f8e84334ea84f5c863edfd9877ae9b996701d25c8affaf83b603b HTTP/1.1" 200 - 2 0.000 0.125
2025-09-27 13:33:40,155 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 1 0.001 0.146
2025-09-27 13:33:40,155 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.1" 200 - 6 0.014 0.102
2025-09-27 13:33:40,178 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "POST /web/action/load HTTP/1.1" 200 - 6 0.006 0.100
2025-09-27 13:33:40,195 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "GET /web/image?model=res.users&field=avatar_128&id=1 HTTP/1.1" 304 - 7 0.017 0.106
2025-09-27 13:33:40,201 17888 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-09-27 13:33:40,255 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "POST /mail/init_messaging HTTP/1.1" 200 - 36 0.069 0.178
2025-09-27 13:33:40,326 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "POST /mail/load_message_failures HTTP/1.1" 200 - 3 0.009 0.031
2025-09-27 13:33:40,529 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "POST /mail/inbox/messages HTTP/1.1" 200 - 4 0.001 0.006
2025-09-27 13:33:40,593 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:40] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 8 0.011 0.010
2025-09-27 13:33:41,923 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:41] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.001 0.010
2025-09-27 13:33:43,955 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:43] "POST /web/action/load HTTP/1.1" 200 - 9 0.009 0.007
2025-09-27 13:33:44,231 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:44] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 26 0.016 0.032
2025-09-27 13:33:44,314 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:44] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.005 0.021
2025-09-27 13:33:44,573 17888 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:44] "GET /base_geoengine/static/lib/geostats-2.0.0/geostats.css HTTP/1.1" 200 - 0 0.000 0.020
2025-09-27 13:33:44,646 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:44] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.000 0.004
2025-09-27 13:33:44,655 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:44] "POST /web/dataset/call_kw/geoengine.vector.layer/fields_get HTTP/1.1" 200 - 8 0.009 0.006
2025-09-27 13:33:44,691 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:44] "POST /web/dataset/call_kw/geoengine.vector.layer/get_views HTTP/1.1" 200 - 7 0.007 0.019
2025-09-27 13:33:44,741 17888 INFO ? werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:44] "GET /base_geoengine/static/lib/geostats-2.0.0/geostats.js HTTP/1.1" 200 - 0 0.000 0.099
2025-09-27 13:33:45,023 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:45] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 10 0.005 0.012
2025-09-27 13:33:45,349 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:45] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.003 0.005
2025-09-27 13:33:45,359 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:45] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.008 0.014
2025-09-27 13:33:59,018 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:59] "POST /web/action/load HTTP/1.1" 200 - 9 0.002 0.008
2025-09-27 13:33:59,377 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:59] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 13 0.005 0.017
2025-09-27 13:33:59,632 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:59] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.003 0.005
2025-09-27 13:33:59,714 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:33:59] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.003 0.006
2025-09-27 13:34:01,549 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:01] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.002 0.002
2025-09-27 13:34:01,945 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:01] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.009 0.010
2025-09-27 13:34:01,959 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:01] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.018 0.016
2025-09-27 13:34:03,390 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:03] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.004 0.008
2025-09-27 13:34:17,473 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:17] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.001 0.016
2025-09-27 13:34:29,946 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:29] "POST /web/dataset/call_kw/customer.map/web_save HTTP/1.1" 200 - 15 0.012 0.014
2025-09-27 13:34:30,305 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:30] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.016 0.014
2025-09-27 13:34:30,323 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:30] "POST /mail/thread/messages HTTP/1.1" 200 - 18 0.022 0.027
2025-09-27 13:34:38,782 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:38] "POST /web/dataset/call_button HTTP/1.1" 200 - 15 0.007 0.023
2025-09-27 13:34:38,831 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2025-09-27 13:34:38,892 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_attachment: filestore gc 4 checked, 2 removed 
2025-09-27 13:34:38,945 17888 INFO ssi_odoo_demo odoo.addons.base.models.res_users: GC'd 0 user log entries 
2025-09-27 13:34:38,996 17888 INFO ssi_odoo_demo odoo.addons.auth_totp.models.auth_totp: GC'd 0 totp devices entries 
2025-09-27 13:34:39,005 17888 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted bus.bus records with IDs: [268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282] 
2025-09-27 13:34:39,145 17888 INFO ssi_odoo_demo odoo.addons.sms.models.sms_sms: GC'd 0 sms marked for deletion 
2025-09-27 13:34:39,341 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Auto-vacuum internal data` (0.510s). 
2025-09-27 13:34:39,348 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Snailmail: process letters queue`. 
2025-09-27 13:34:39,354 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Snailmail: process letters queue` (0.004s). 
2025-09-27 13:34:39,360 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `SMS: SMS Queue Manager`. 
2025-09-27 13:34:39,363 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `SMS: SMS Queue Manager` (0.003s). 
2025-09-27 13:34:39,369 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Partner Autocomplete: Sync with remote DB`. 
2025-09-27 13:34:39,371 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Partner Autocomplete: Sync with remote DB` (0.002s). 
2025-09-27 13:34:39,376 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Notification: Send scheduled message notifications`. 
2025-09-27 13:34:39,380 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Notification: Send scheduled message notifications` (0.004s). 
2025-09-27 13:34:39,386 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Mail: Email Queue Manager`. 
2025-09-27 13:34:39,392 17888 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Mail: Email Queue Manager` (0.006s). 
2025-09-27 13:34:49,180 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:49] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.003 0.003
2025-09-27 13:34:58,553 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:34:58] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.002 0.004
2025-09-27 13:35:05,485 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:05] "POST /web/dataset/call_kw/customer.map/web_save HTTP/1.1" 200 - 12 0.001 0.031
2025-09-27 13:35:05,735 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:05] "POST /mail/thread/messages HTTP/1.1" 200 - 20 0.003 0.017
2025-09-27 13:35:05,812 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:05] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.002 0.007
2025-09-27 13:35:18,268 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:18] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.000 0.005
2025-09-27 13:35:31,065 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:31] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.000 0.009
2025-09-27 13:35:39,541 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:39] "POST /web/dataset/call_kw/customer.map/web_save HTTP/1.1" 200 - 4 0.001 0.015
2025-09-27 13:35:39,869 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:39] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.000 0.012
2025-09-27 13:35:39,873 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:39] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.002 0.014
2025-09-27 13:35:46,476 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:46] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.001 0.006
2025-09-27 13:35:46,796 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:46] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.001 0.007
2025-09-27 13:35:47,057 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:47] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.006 0.011
2025-09-27 13:35:47,121 17888 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:35:47] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.002 0.008
2025-09-27 13:58:23,702 17888 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-27 13:58:23,702 17888 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-27 13:58:24,273 17888 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
2025-09-27 13:58:26,866 13036 INFO ? odoo: Odoo version 17.0 
2025-09-27 13:58:26,866 13036 INFO ? odoo: Using configuration file at D:\work-project\ssi\odoo_demo\odoo\odoo.conf 
2025-09-27 13:58:26,866 13036 INFO ? odoo: addons paths: ['D:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\data\\addons\\17.0', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\field_service', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\geospatial', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons'] 
2025-09-27 13:58:26,866 13036 INFO ? odoo: database: odoo@localhost:5432 
2025-09-27 13:58:27,107 13036 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-27 13:58:27,412 13036 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-27 13:58:27,425 13036 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-27 13:58:27,471 13036 INFO ssi_odoo_demo odoo.modules.loading: loading 1 modules... 
2025-09-27 13:58:27,477 13036 INFO ssi_odoo_demo odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-27 13:58:27,495 13036 INFO ssi_odoo_demo odoo.modules.loading: updating modules list 
2025-09-27 13:58:27,495 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-27 13:58:28,702 13036 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 13:58:28,857 13036 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'stock_qr_tracking', defaulting to LGPL-3 
2025-09-27 13:58:29,128 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 13:58:29,128 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 13:58:29,723 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-27 13:58:29,760 13036 INFO ssi_odoo_demo odoo.modules.loading: loading 77 modules... 
2025-09-27 13:58:30,345 13036 INFO ssi_odoo_demo odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 13:58:30,395 13036 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.customer_map_tracking.models.customer_map is not overriding the create method in batch 
2025-09-27 13:58:30,438 13036 INFO ssi_odoo_demo odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 13:58:30,518 13036 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 13:58:30,598 13036 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 13:58:30,615 13036 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 13:58:30,646 13036 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 13:58:30,662 13036 WARNING ssi_odoo_demo odoo.addons.base.models.ir_ui_view: A <i> with fa class (fa fa-phone) must have title in its tag, parents, descendants or have text
View error context:
{'file': 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\customer_map_tracking\\views\\customer_map_geoengine_views.xml',
 'line': 25,
 'name': 'customer.map.geoengine',
 'view': ir.ui.view(2224,),
 'view.model': 'customer.map',
 'view.parent': ir.ui.view(),
 'xmlid': 'view_customer_map_geoengine'} 
2025-09-27 13:58:30,662 13036 WARNING ssi_odoo_demo odoo.addons.base.models.ir_ui_view: A <i> with fa class (fa fa-envelope) must have title in its tag, parents, descendants or have text
View error context:
{'file': 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\customer_map_tracking\\views\\customer_map_geoengine_views.xml',
 'line': 29,
 'name': 'customer.map.geoengine',
 'view': ir.ui.view(2224,),
 'view.model': 'customer.map',
 'view.parent': ir.ui.view(),
 'xmlid': 'view_customer_map_geoengine'} 
2025-09-27 13:58:30,662 13036 WARNING ssi_odoo_demo odoo.addons.base.models.ir_ui_view: A <i> with fa class (fa fa-map-marker) must have title in its tag, parents, descendants or have text
View error context:
{'file': 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\customer_map_tracking\\views\\customer_map_geoengine_views.xml',
 'line': 33,
 'name': 'customer.map.geoengine',
 'view': ir.ui.view(2224,),
 'view.model': 'customer.map',
 'view.parent': ir.ui.view(),
 'xmlid': 'view_customer_map_geoengine'} 
2025-09-27 13:58:30,677 13036 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 13:58:30,692 13036 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 13:58:30,711 13036 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 13:58:31,025 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-27 13:58:31,025 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:31,397 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:31,397 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:31,753 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:31,753 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:32,160 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:32,160 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:32,577 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:32,577 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:32,985 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:32,985 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:33,413 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:33,413 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:33,771 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:33,771 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:34,178 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:34,178 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:34,591 13036 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 13:58:34,591 13036 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 13:58:34,641 13036 INFO ssi_odoo_demo odoo.modules.loading: Module customer_map_tracking loaded in 4.30s, 5191 queries (+5191 other) 
2025-09-27 13:58:35,377 13036 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.product_master.models.product_template is not overriding the create method in batch 
2025-09-27 13:58:35,396 13036 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.purchase_fsm_assignment_api.models.installation_checklist is not overriding the create method in batch 
2025-09-27 13:58:35,446 13036 INFO ssi_odoo_demo odoo.modules.loading: 77 modules loaded in 5.69s, 5191 queries (+5191 extra) 
2025-09-27 13:58:35,614 13036 WARNING ssi_odoo_demo py.warnings: D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py:536: UserWarning: Property fsm.size.name.required should be a boolean (True).
  File "D:\work-project\ssi\odoo_demo\odoo\odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\command.py", line 67, in main
    o.run(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 186, in run
    main(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 179, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1469, in start
    rc = server.run(preload, stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 635, in run
    rc = preload_registries(preload)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 493, in load_modules
    registry.setup_models(cr)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 319, in setup_models
    model._setup_fields()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 3420, in _setup_fields
    field.setup(self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py", line 536, in setup
    warnings.warn(f'Property {self}.required should be a boolean ({self.required}).')
 
2025-09-27 13:58:35,991 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 102@geoengine.raster.layer (customer_map_tracking.customer_map_raster_osm_detailed) 
2025-09-27 13:58:36,026 13036 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [64025] 
2025-09-27 13:58:36,026 13036 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted geoengine.raster.layer records with IDs: [102] 
2025-09-27 13:58:36,026 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 128@geoengine.vector.layer (customer_map_tracking.customer_map_vector_layer_detailed) 
2025-09-27 13:58:36,034 13036 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [64024] 
2025-09-27 13:58:36,034 13036 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted geoengine.vector.layer records with IDs: [128] 
2025-09-27 13:58:36,043 13036 INFO ssi_odoo_demo odoo.modules.registry: verifying fields for every extended model 
2025-09-27 13:58:36,753 13036 INFO ssi_odoo_demo odoo.modules.loading: Modules loaded. 
2025-09-27 13:58:36,757 13036 INFO ssi_odoo_demo odoo.modules.registry: Registry loaded in 9.346s 
2025-09-27 13:58:36,820 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-27 13:58:36,839 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:58:36] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 5 0.003 9.096
2025-09-27 13:58:37,173 13036 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-09-27 13:58:46,336 13036 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 13:58:46,721 13036 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 180. Replace by @t-out 
2025-09-27 13:58:46,721 13036 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 180. Replace by @t-out 
2025-09-27 13:58:46,721 13036 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 180. Replace by @t-out 
2025-09-27 13:58:46,732 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:58:46] "GET /web HTTP/1.1" 200 - 76 0.031 0.576
2025-09-27 13:58:55,791 13036 INFO ssi_odoo_demo odoo.addons.base.models.assetsbundle: Generating a new asset bundle attachment /web/assets/04baa0f/web.assets_web.min.css (id:527) 
2025-09-27 13:58:55,791 13036 INFO ssi_odoo_demo odoo.addons.base.models.assetsbundle: Deleting attachments [525] (matching /web/assets/_______/web.assets_web.min.css) because it was replaced with /web/assets/04baa0f/web.assets_web.min.css 
2025-09-27 13:58:55,871 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:58:55] "GET /web/assets/04baa0f/web.assets_web.min.css HTTP/1.1" 200 - 31 0.082 9.024
2025-09-27 13:59:17,069 13036 INFO ssi_odoo_demo odoo.addons.base.models.assetsbundle: Generating a new asset bundle attachment /web/assets/a064fa8/web.assets_web.min.js (id:528) 
2025-09-27 13:59:17,070 13036 INFO ssi_odoo_demo odoo.addons.base.models.assetsbundle: Deleting attachments [526] (matching /web/assets/_______/web.assets_web.min.js) because it was replaced with /web/assets/a064fa8/web.assets_web.min.js 
2025-09-27 13:59:17,736 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:17] "GET /web/assets/a064fa8/web.assets_web.min.js HTTP/1.1" 200 - 27 0.039 30.931
2025-09-27 13:59:18,411 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.1" 200 - 7 0.017 0.090
2025-09-27 13:59:18,411 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "POST /web/action/load HTTP/1.1" 200 - 11 0.035 0.102
2025-09-27 13:59:18,424 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "GET /web/image?model=res.users&field=avatar_128&id=1 HTTP/1.1" 304 - 7 0.004 0.095
2025-09-27 13:59:18,454 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "POST /mail/init_messaging HTTP/1.1" 200 - 36 0.075 0.105
2025-09-27 13:59:18,569 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 26 0.020 0.024
2025-09-27 13:59:18,760 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "POST /mail/load_message_failures HTTP/1.1" 200 - 3 0.014 0.008
2025-09-27 13:59:18,785 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 8 0.009 0.006
2025-09-27 13:59:18,814 13036 ERROR ssi_odoo_demo odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1971, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\model.py", line 152, in retrying
    result = func()
             ^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1999, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2203, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\addons\base\models\ir_http.py", line 221, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 786, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\controllers\dataset.py", line 25, in call_kw
    return self._call_kw(model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\controllers\dataset.py", line 21, in _call_kw
    return call_kw(Model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\api.py", line 480, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\api.py", line 451, in _call_kw_model
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\models\models.py", line 46, in web_search_read
    records = self.search_fetch(domain, specification.keys(), offset=offset, limit=limit, order=order)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 1646, in search_fetch
    query = self._search(domain, offset=offset, limit=limit, order=order or self._order)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5444, in _search
    query = self._where_calc(domain)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5155, in _where_calc
    return expression.expression(domain, self).query
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\osv\expression.py", line 805, in __init__
    self.parse()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\osv\expression.py", line 1475, in parse
    push_result(self.__leaf_to_sql(leaf, model, alias))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\custom_addons\geospatial\base_geoengine\expressions.py", line 88, in __leaf_to_sql
    query = get_geo_func(
            ^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\custom_addons\geospatial\base_geoengine\expressions.py", line 115, in get_geo_func
    raise NotImplementedError(f"The operator {operator} is not supported")
NotImplementedError: The operator != is not supported
2025-09-27 13:59:18,816 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:18] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 1 0.000 0.061
2025-09-27 13:59:20,346 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:20] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.000 0.001
2025-09-27 13:59:26,112 13036 ERROR ssi_odoo_demo odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1971, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\model.py", line 152, in retrying
    result = func()
             ^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1999, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2203, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\addons\base\models\ir_http.py", line 221, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 786, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\controllers\dataset.py", line 25, in call_kw
    return self._call_kw(model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\controllers\dataset.py", line 21, in _call_kw
    return call_kw(Model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\api.py", line 480, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\api.py", line 451, in _call_kw_model
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\models\models.py", line 46, in web_search_read
    records = self.search_fetch(domain, specification.keys(), offset=offset, limit=limit, order=order)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 1646, in search_fetch
    query = self._search(domain, offset=offset, limit=limit, order=order or self._order)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5444, in _search
    query = self._where_calc(domain)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5155, in _where_calc
    return expression.expression(domain, self).query
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\osv\expression.py", line 805, in __init__
    self.parse()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\osv\expression.py", line 1475, in parse
    push_result(self.__leaf_to_sql(leaf, model, alias))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\custom_addons\geospatial\base_geoengine\expressions.py", line 88, in __leaf_to_sql
    query = get_geo_func(
            ^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\custom_addons\geospatial\base_geoengine\expressions.py", line 115, in get_geo_func
    raise NotImplementedError(f"The operator {operator} is not supported")
NotImplementedError: The operator != is not supported
2025-09-27 13:59:26,116 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:26] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 1 0.000 0.009
2025-09-27 13:59:30,132 13036 ERROR ssi_odoo_demo odoo.http: Exception during request handling. 
Traceback (most recent call last):
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2396, in __call__
    response = request._serve_db()
               ^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1971, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\model.py", line 152, in retrying
    result = func()
             ^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 1999, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 2203, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\addons\base\models\ir_http.py", line 221, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\http.py", line 786, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\controllers\dataset.py", line 25, in call_kw
    return self._call_kw(model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\controllers\dataset.py", line 21, in _call_kw
    return call_kw(Model, method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\api.py", line 480, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\api.py", line 451, in _call_kw_model
    result = method(recs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\addons\web\models\models.py", line 46, in web_search_read
    records = self.search_fetch(domain, specification.keys(), offset=offset, limit=limit, order=order)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 1646, in search_fetch
    query = self._search(domain, offset=offset, limit=limit, order=order or self._order)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5444, in _search
    query = self._where_calc(domain)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 5155, in _where_calc
    return expression.expression(domain, self).query
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\osv\expression.py", line 805, in __init__
    self.parse()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\osv\expression.py", line 1475, in parse
    push_result(self.__leaf_to_sql(leaf, model, alias))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\custom_addons\geospatial\base_geoengine\expressions.py", line 88, in __leaf_to_sql
    query = get_geo_func(
            ^^^^^^^^^^^^^
  File "d:\work-project\ssi\odoo_demo\odoo\custom_addons\geospatial\base_geoengine\expressions.py", line 115, in get_geo_func
    raise NotImplementedError(f"The operator {operator} is not supported")
NotImplementedError: The operator != is not supported
2025-09-27 13:59:30,134 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:30] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 1 0.000 0.009
2025-09-27 13:59:32,480 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:32] "POST /web/action/load HTTP/1.1" 200 - 9 0.007 0.001
2025-09-27 13:59:32,755 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:32] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 14 0.016 0.020
2025-09-27 13:59:32,814 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:32] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.002 0.002
2025-09-27 13:59:33,077 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:33] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.000 0.004
2025-09-27 13:59:34,566 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:34] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.002 0.004
2025-09-27 13:59:35,041 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:35] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.015 0.085
2025-09-27 13:59:35,084 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:35] "POST /mail/thread/messages HTTP/1.1" 200 - 21 0.110 0.018
2025-09-27 13:59:36,813 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2025-09-27 13:59:36,858 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_attachment: filestore gc 4 checked, 2 removed 
2025-09-27 13:59:36,906 13036 INFO ssi_odoo_demo odoo.addons.base.models.res_users: GC'd 0 user log entries 
2025-09-27 13:59:36,941 13036 INFO ssi_odoo_demo odoo.addons.auth_totp.models.auth_totp: GC'd 0 totp devices entries 
2025-09-27 13:59:36,955 13036 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted bus.bus records with IDs: [283, 284] 
2025-09-27 13:59:37,061 13036 INFO ssi_odoo_demo odoo.addons.sms.models.sms_sms: GC'd 0 sms marked for deletion 
2025-09-27 13:59:37,213 13036 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Auto-vacuum internal data` (0.400s). 
2025-09-27 13:59:39,712 13036 WARNING ssi_odoo_demo odoo.http: No raster layer for view customer.map.geoengine 
2025-09-27 13:59:39,712 13036 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 13:59:39] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 5 0.004 0.002
2025-09-27 14:00:53,403 13036 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-27 14:00:53,403 13036 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-27 14:00:53,631 13036 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 8 connections  
2025-09-27 14:00:56,881 13692 INFO ? odoo: Odoo version 17.0 
2025-09-27 14:00:56,881 13692 INFO ? odoo: Using configuration file at D:\work-project\ssi\odoo_demo\odoo\odoo.conf 
2025-09-27 14:00:56,881 13692 INFO ? odoo: addons paths: ['D:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\data\\addons\\17.0', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\field_service', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\geospatial', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons'] 
2025-09-27 14:00:56,881 13692 INFO ? odoo: database: odoo@localhost:5432 
2025-09-27 14:00:57,070 13692 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-27 14:00:57,362 13692 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-27 14:00:57,365 13692 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-27 14:00:57,409 13692 INFO ssi_odoo_demo odoo.modules.loading: loading 1 modules... 
2025-09-27 14:00:57,409 13692 INFO ssi_odoo_demo odoo.modules.loading: 1 modules loaded in 0.00s, 0 queries (+0 extra) 
2025-09-27 14:00:57,431 13692 INFO ssi_odoo_demo odoo.modules.loading: updating modules list 
2025-09-27 14:00:57,442 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-27 14:00:58,466 13692 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 14:00:58,605 13692 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'stock_qr_tracking', defaulting to LGPL-3 
2025-09-27 14:00:58,845 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 14:00:58,845 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 14:00:59,591 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-27 14:00:59,620 13692 INFO ssi_odoo_demo odoo.modules.loading: loading 77 modules... 
2025-09-27 14:01:00,156 13692 INFO ssi_odoo_demo odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 14:01:00,208 13692 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.customer_map_tracking.models.customer_map is not overriding the create method in batch 
2025-09-27 14:01:00,245 13692 INFO ssi_odoo_demo odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 14:01:00,317 13692 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 14:01:00,405 13692 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 14:01:00,427 13692 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 14:01:00,448 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_ui_view: Could not find view arch definition in file 'd:\work-project\ssi\odoo_demo\odoo\custom_addons\customer_map_tracking\views\customer_map_geoengine_views.xml' for xmlid 'customer_map_tracking.view_customer_map_form_geo_edit' 
2025-09-27 14:01:00,456 13692 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 14:01:00,492 13692 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 14:01:00,498 13692 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 14:01:00,518 13692 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 14:01:00,854 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-27 14:01:00,855 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:01,209 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:01,210 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:01,568 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:01,568 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:01,862 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:01,862 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:02,223 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:02,223 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:02,526 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:02,526 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:02,857 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:02,858 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:03,223 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:03,223 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:03,591 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:03,591 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:03,945 13692 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:01:03,945 13692 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:01:03,995 13692 INFO ssi_odoo_demo odoo.modules.loading: Module customer_map_tracking loaded in 3.84s, 5133 queries (+5133 other) 
2025-09-27 14:01:04,695 13692 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.product_master.models.product_template is not overriding the create method in batch 
2025-09-27 14:01:04,704 13692 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.purchase_fsm_assignment_api.models.installation_checklist is not overriding the create method in batch 
2025-09-27 14:01:04,749 13692 INFO ssi_odoo_demo odoo.modules.loading: 77 modules loaded in 5.13s, 5133 queries (+5133 extra) 
2025-09-27 14:01:04,913 13692 WARNING ssi_odoo_demo py.warnings: D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py:536: UserWarning: Property fsm.size.name.required should be a boolean (True).
  File "D:\work-project\ssi\odoo_demo\odoo\odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\command.py", line 67, in main
    o.run(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 186, in run
    main(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 179, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1469, in start
    rc = server.run(preload, stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 635, in run
    rc = preload_registries(preload)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 493, in load_modules
    registry.setup_models(cr)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 319, in setup_models
    model._setup_fields()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 3420, in _setup_fields
    field.setup(self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py", line 536, in setup
    warnings.warn(f'Property {self}.required should be a boolean ({self.required}).')
 
2025-09-27 14:01:05,227 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 593@ir.actions.act_window (customer_map_tracking.action_customer_map_editor) 
2025-09-27 14:01:05,291 13692 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [64119] 
2025-09-27 14:01:05,291 13692 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.actions.act_window records with IDs: [593] 
2025-09-27 14:01:05,291 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_model: Deleting 2225@ir.ui.view (customer_map_tracking.view_customer_map_form_geo_edit) 
2025-09-27 14:01:05,312 13692 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [64115] 
2025-09-27 14:01:05,312 13692 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted ir.ui.view records with IDs: [2225] 
2025-09-27 14:01:05,319 13692 INFO ssi_odoo_demo odoo.modules.registry: verifying fields for every extended model 
2025-09-27 14:01:05,973 13692 INFO ssi_odoo_demo odoo.modules.loading: Modules loaded. 
2025-09-27 14:01:05,987 13692 INFO ssi_odoo_demo odoo.modules.registry: Registry loaded in 8.623s 
2025-09-27 14:01:06,084 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-27 14:01:06,109 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:06] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 5 0.010 8.507
2025-09-27 14:01:06,296 13692 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 14:01:06,435 13692 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-09-27 14:01:06,723 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 180. Replace by @t-out 
2025-09-27 14:01:06,723 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 180. Replace by @t-out 
2025-09-27 14:01:06,723 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 180. Replace by @t-out 
2025-09-27 14:01:06,729 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:06] "GET /web HTTP/1.1" 200 - 79 0.105 7.219
2025-09-27 14:01:06,972 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:06] "POST /mail/init_messaging HTTP/1.1" 200 - 36 0.035 0.028
2025-09-27 14:01:07,079 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "POST /web/action/load HTTP/1.1" 200 - 10 0.007 0.176
2025-09-27 14:01:07,261 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "POST /web/dataset/call_kw/res.users/systray_get_activities HTTP/1.1" 200 - 6 0.000 0.009
2025-09-27 14:01:07,295 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "POST /mail/load_message_failures HTTP/1.1" 200 - 3 0.000 0.008
2025-09-27 14:01:07,336 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 22 0.022 0.027
2025-09-27 14:01:07,409 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.000 0.006
2025-09-27 14:01:07,680 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.012 0.004
2025-09-27 14:01:07,787 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "GET /web/image?model=res.users&field=avatar_128&id=1 HTTP/1.1" 304 - 7 0.000 0.015
2025-09-27 14:01:07,799 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:07] "POST /mail/thread/messages HTTP/1.1" 200 - 21 0.027 0.017
2025-09-27 14:01:08,108 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:08] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 8 0.001 0.004
2025-09-27 14:01:09,737 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:09] "GET /web/service-worker.js HTTP/1.1" 200 - 1 0.000 0.004
2025-09-27 14:01:10,185 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:10] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.003 0.009
2025-09-27 14:01:15,781 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:15] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.000 0.009
2025-09-27 14:01:19,823 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:19] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.001 0.005
2025-09-27 14:01:20,126 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:20] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.003 0.001
2025-09-27 14:01:21,663 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:21] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.008 0.000
2025-09-27 14:01:21,946 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:21] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.010 0.012
2025-09-27 14:01:22,021 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:22] "POST /mail/thread/messages HTTP/1.1" 200 - 18 0.017 0.014
2025-09-27 14:01:24,492 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:24] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.004 0.010
2025-09-27 14:01:49,201 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:01:49] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.002 0.009
2025-09-27 14:02:06,119 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2025-09-27 14:02:06,166 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_attachment: filestore gc 0 checked, 0 removed 
2025-09-27 14:02:06,219 13692 INFO ssi_odoo_demo odoo.addons.base.models.res_users: GC'd 0 user log entries 
2025-09-27 14:02:06,251 13692 INFO ssi_odoo_demo odoo.addons.auth_totp.models.auth_totp: GC'd 0 totp devices entries 
2025-09-27 14:02:06,273 13692 INFO ssi_odoo_demo odoo.models.unlink: User #1 deleted bus.bus records with IDs: [285, 286, 287] 
2025-09-27 14:02:06,391 13692 INFO ssi_odoo_demo odoo.addons.sms.models.sms_sms: GC'd 0 sms marked for deletion 
2025-09-27 14:02:06,553 13692 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Auto-vacuum internal data` (0.434s). 
2025-09-27 14:02:07,569 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:07] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.000 0.006
2025-09-27 14:02:10,487 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:10] "POST /web/dataset/call_kw/customer.map/web_save HTTP/1.1" 200 - 6 0.009 0.022
2025-09-27 14:02:10,727 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:10] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.005 0.006
2025-09-27 14:02:10,823 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:10] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.001 0.015
2025-09-27 14:02:19,193 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:19] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.002 0.003
2025-09-27 14:02:22,246 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:22] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.000 0.005
2025-09-27 14:02:22,527 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:22] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.008 0.014
2025-09-27 14:02:22,577 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:22] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.000 0.005
2025-09-27 14:02:28,678 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:28] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.006 0.008
2025-09-27 14:02:40,628 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:40] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.001 0.006
2025-09-27 14:02:42,681 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:42] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.003 0.004
2025-09-27 14:02:56,838 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:56] "POST /web/dataset/call_kw/customer.map/onchange HTTP/1.1" 200 - 2 0.000 0.008
2025-09-27 14:02:58,783 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:58] "POST /web/dataset/call_kw/customer.map/web_save HTTP/1.1" 200 - 4 0.002 0.005
2025-09-27 14:02:59,112 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:59] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.000 0.006
2025-09-27 14:02:59,129 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:02:59] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.014 0.007
2025-09-27 14:03:07,956 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:07] "GET /web/service-worker.js HTTP/1.1" 200 - 3 0.010 0.005
2025-09-27 14:03:08,246 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 180. Replace by @t-out 
2025-09-27 14:03:08,247 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 180. Replace by @t-out 
2025-09-27 14:03:08,247 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 180. Replace by @t-out 
2025-09-27 14:03:08,249 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:08] "GET /web/offline HTTP/1.1" 200 - 13 0.001 0.041
2025-09-27 14:03:10,398 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:10] "POST /web/dataset/call_button HTTP/1.1" 200 - 1 0.001 0.002
2025-09-27 14:03:10,755 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:10] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 10 0.008 0.024
2025-09-27 14:03:10,978 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:10] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.002 0.008
2025-09-27 14:03:11,095 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:11] "POST /web/dataset/call_kw/geoengine.vector.layer/fields_get HTTP/1.1" 200 - 8 0.003 0.015
2025-09-27 14:03:11,305 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:11] "POST /web/dataset/call_kw/res.users/has_group HTTP/1.1" 200 - 2 0.000 0.002
2025-09-27 14:03:11,327 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:11] "POST /web/dataset/call_kw/geoengine.vector.layer/get_views HTTP/1.1" 200 - 7 0.018 0.004
2025-09-27 14:03:11,423 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:11] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 10 0.003 0.015
2025-09-27 14:03:11,659 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:11] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.006 0.008
2025-09-27 14:03:11,747 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:11] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.001 0.007
2025-09-27 14:03:16,845 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:16] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.000 0.004
2025-09-27 14:03:19,571 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:19] "POST /web/action/load HTTP/1.1" 200 - 10 0.009 0.009
2025-09-27 14:03:19,845 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:19] "POST /web/dataset/call_kw/customer.map/get_views HTTP/1.1" 200 - 16 0.011 0.032
2025-09-27 14:03:19,903 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:19] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.000 0.011
2025-09-27 14:03:20,171 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:20] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.008 0.008
2025-09-27 14:03:20,246 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:20] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.009 0.015
2025-09-27 14:03:20,493 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:20] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.003 0.011
2025-09-27 14:03:24,557 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:24] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.001 0.004
2025-09-27 14:03:26,177 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:26] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.004 0.005
2025-09-27 14:03:26,445 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:26] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.004 0.015
2025-09-27 14:03:26,527 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:26] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.007 0.015
2025-09-27 14:03:26,787 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:26] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.000 0.012
2025-09-27 14:03:40,627 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:40] "GET /web/manifest.webmanifest HTTP/1.1" 200 - 7 0.003 0.011
2025-09-27 14:03:40,806 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 181. Replace by @t-out 
2025-09-27 14:03:40,807 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 181. Replace by @t-out 
2025-09-27 14:03:40,808 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 181. Replace by @t-out 
2025-09-27 14:03:41,065 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="title or 'Odoo'" in template 180. Replace by @t-out 
2025-09-27 14:03:41,065 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='request.csrf_token(None)' in template 180. Replace by @t-out 
2025-09-27 14:03:41,066 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc='debug' in template 180. Replace by @t-out 
2025-09-27 14:03:41,072 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:41] "GET /web HTTP/1.1" 200 - 42 0.026 0.758
2025-09-27 14:03:41,338 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="user_id.name[:23] + '...' if user_id.name and len(user_id.name) > 25 else user_id.name" in template 539. Replace by @t-out 
2025-09-27 14:03:41,356 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="active_lang[2].split('/').pop()" in template 538. Replace by @t-out 
2025-09-27 14:03:41,357 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="active_lang[1].split('_').pop(0).upper()" in template 538. Replace by @t-out 
2025-09-27 14:03:41,360 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="lg[2].split('/').pop()" in template 538. Replace by @t-out 
2025-09-27 14:03:41,361 13692 WARNING ssi_odoo_demo odoo.addons.base.models.ir_qweb: Found deprecated directive @t-esc="lg[1].split('_').pop(0).upper()" in template 538. Replace by @t-out 
2025-09-27 14:03:41,388 13692 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:03:41] "GET /.well-known/appspecific/com.chrome.devtools.json HTTP/1.1" 404 - 79 0.065 0.708
2025-09-27 14:03:54,281 13692 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-27 14:03:54,281 13692 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-27 14:03:55,388 13692 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 6 connections  
2025-09-27 14:37:57,573 6268 INFO ? odoo: Odoo version 17.0 
2025-09-27 14:37:57,573 6268 INFO ? odoo: Using configuration file at D:\work-project\ssi\odoo_demo\odoo\odoo.conf 
2025-09-27 14:37:57,573 6268 INFO ? odoo: addons paths: ['D:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\data\\addons\\17.0', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\field_service', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\geospatial', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons'] 
2025-09-27 14:37:57,573 6268 INFO ? odoo: database: odoo@localhost:5432 
2025-09-27 14:37:57,877 6268 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-27 14:37:58,300 6268 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-27 14:37:58,310 6268 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-27 14:37:58,373 6268 INFO ssi_odoo_demo odoo.modules.loading: loading 1 modules... 
2025-09-27 14:37:58,380 6268 INFO ssi_odoo_demo odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-27 14:37:58,401 6268 INFO ssi_odoo_demo odoo.modules.loading: updating modules list 
2025-09-27 14:37:58,405 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-27 14:37:59,654 6268 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 14:37:59,808 6268 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'stock_qr_tracking', defaulting to LGPL-3 
2025-09-27 14:38:00,052 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 14:38:00,052 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-27 14:38:00,796 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-27 14:38:00,839 6268 INFO ssi_odoo_demo odoo.modules.loading: loading 77 modules... 
2025-09-27 14:38:01,589 6268 INFO ssi_odoo_demo odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-27 14:38:01,643 6268 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.customer_map_tracking.models.customer_map is not overriding the create method in batch 
2025-09-27 14:38:01,682 6268 INFO ssi_odoo_demo odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-27 14:38:01,815 6268 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-27 14:38:01,923 6268 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-27 14:38:01,946 6268 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-27 14:38:01,982 6268 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-27 14:38:02,008 6268 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-27 14:38:02,015 6268 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-27 14:38:02,041 6268 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-27 14:38:02,418 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-27 14:38:02,418 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:02,787 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:02,787 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:03,146 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:03,146 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:03,501 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:03,501 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:03,863 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:03,863 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:04,255 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:04,255 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:04,613 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:04,613 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:04,980 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:04,980 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:05,346 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:05,346 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:05,723 6268 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-27 14:38:05,723 6268 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-27 14:38:05,791 6268 INFO ssi_odoo_demo odoo.modules.loading: Module customer_map_tracking loaded in 4.20s, 5128 queries (+5128 other) 
2025-09-27 14:38:06,767 6268 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.product_master.models.product_template is not overriding the create method in batch 
2025-09-27 14:38:06,777 6268 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.purchase_fsm_assignment_api.models.installation_checklist is not overriding the create method in batch 
2025-09-27 14:38:06,833 6268 INFO ssi_odoo_demo odoo.modules.loading: 77 modules loaded in 5.99s, 5128 queries (+5128 extra) 
2025-09-27 14:38:07,002 6268 WARNING ssi_odoo_demo py.warnings: D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py:536: UserWarning: Property fsm.size.name.required should be a boolean (True).
  File "D:\work-project\ssi\odoo_demo\odoo\odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\command.py", line 67, in main
    o.run(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 186, in run
    main(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 179, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1469, in start
    rc = server.run(preload, stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 635, in run
    rc = preload_registries(preload)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 493, in load_modules
    registry.setup_models(cr)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 319, in setup_models
    model._setup_fields()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 3420, in _setup_fields
    field.setup(self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py", line 536, in setup
    warnings.warn(f'Property {self}.required should be a boolean ({self.required}).')
 
2025-09-27 14:38:07,329 6268 INFO ssi_odoo_demo odoo.modules.registry: verifying fields for every extended model 
2025-09-27 14:38:08,013 6268 INFO ssi_odoo_demo odoo.modules.loading: Modules loaded. 
2025-09-27 14:38:08,023 6268 INFO ssi_odoo_demo odoo.modules.registry: Registry loaded in 9.722s 
2025-09-27 14:38:45,883 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-27 14:38:45,921 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:38:45] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 5 0.003 0.037
2025-09-27 14:38:46,255 6268 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-09-27 14:39:08,175 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Base: Auto-vacuum internal data`. 
2025-09-27 14:39:08,227 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_attachment: filestore gc 0 checked, 0 removed 
2025-09-27 14:39:08,291 6268 INFO ssi_odoo_demo odoo.addons.base.models.res_users: GC'd 0 user log entries 
2025-09-27 14:39:08,333 6268 INFO ssi_odoo_demo odoo.addons.auth_totp.models.auth_totp: GC'd 0 totp devices entries 
2025-09-27 14:39:08,446 6268 INFO ssi_odoo_demo odoo.addons.sms.models.sms_sms: GC'd 0 sms marked for deletion 
2025-09-27 14:39:08,583 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Base: Auto-vacuum internal data` (0.409s). 
2025-09-27 14:39:08,589 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `SMS: SMS Queue Manager`. 
2025-09-27 14:39:08,593 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `SMS: SMS Queue Manager` (0.004s). 
2025-09-27 14:39:08,598 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Partner Autocomplete: Sync with remote DB`. 
2025-09-27 14:39:08,600 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Partner Autocomplete: Sync with remote DB` (0.002s). 
2025-09-27 14:39:08,604 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Snailmail: process letters queue`. 
2025-09-27 14:39:08,608 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Snailmail: process letters queue` (0.004s). 
2025-09-27 14:39:08,613 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Notification: Send scheduled message notifications`. 
2025-09-27 14:39:08,613 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Notification: Send scheduled message notifications` (0.000s). 
2025-09-27 14:39:08,621 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Mail: Email Queue Manager`. 
2025-09-27 14:39:08,629 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Mail: Email Queue Manager` (0.008s). 
2025-09-27 14:39:08,633 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Starting job `Calendar: Event Reminder`. 
2025-09-27 14:39:08,646 6268 INFO ssi_odoo_demo odoo.addons.base.models.ir_cron: Job done: `Calendar: Event Reminder` (0.013s). 
2025-09-27 14:40:44,929 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:40:44] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 3 0.001 0.080
2025-09-27 14:40:49,883 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:40:49] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.001 0.005
2025-09-27 14:40:50,276 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:40:50] "POST /mail/thread/data HTTP/1.1" 200 - 11 0.018 0.035
2025-09-27 14:40:50,296 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:40:50] "POST /mail/thread/messages HTTP/1.1" 200 - 19 0.032 0.030
2025-09-27 14:40:53,991 6268 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-27 14:40:54,066 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:40:54] "GET /web/bundle/web.assets_emoji?lang=en_US&debug=1 HTTP/1.1" 200 - 4 0.006 0.104
2025-09-27 14:40:54,473 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:40:54] "GET /web/assets/71ab915/web.assets_emoji.min.js HTTP/1.1" 200 - 4 0.003 0.096
2025-09-27 14:41:00,831 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:00] "POST /web/dataset/call_kw/mail.activity.schedule/get_views HTTP/1.1" 200 - 14 0.019 0.052
2025-09-27 14:41:01,177 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:01] "POST /web/dataset/call_kw/mail.activity.schedule/onchange HTTP/1.1" 200 - 7 0.025 0.008
2025-09-27 14:41:01,477 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:01] "GET /web/bundle/web_editor.backend_assets_wysiwyg?lang=en_US&debug=1 HTTP/1.1" 200 - 7 0.002 0.061
2025-09-27 14:41:01,623 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:01] "POST /web/dataset/call_kw/ir.ui.view/render_public_asset HTTP/1.1" 200 - 9 0.010 0.068
2025-09-27 14:41:01,991 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:01] "GET /web/image/res.users/1/avatar_128 HTTP/1.1" 200 - 7 0.002 0.009
2025-09-27 14:41:03,651 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:03] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.000 0.007
2025-09-27 14:41:03,974 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:03] "POST /mail/thread/data HTTP/1.1" 200 - 3 0.006 0.002
2025-09-27 14:41:13,224 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:13] "POST /web/dataset/call_button HTTP/1.1" 200 - 1 0.006 0.004
2025-09-27 14:41:21,680 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:21] "POST /web/dataset/call_kw/customer.map/get_edit_info_for_geo_column HTTP/1.1" 200 - 8 0.004 0.009
2025-09-27 14:41:47,339 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:47] "POST /web/dataset/call_kw/customer.map/web_save HTTP/1.1" 200 - 9 0.011 0.014
2025-09-27 14:41:47,600 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:47] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.014 0.015
2025-09-27 14:41:47,680 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:47] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.003 0.009
2025-09-27 14:41:50,301 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:50] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.000 0.005
2025-09-27 14:41:50,658 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:50] "POST /mail/thread/messages HTTP/1.1" 200 - 3 0.015 0.011
2025-09-27 14:41:50,663 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:50] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.010 0.024
2025-09-27 14:41:51,303 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:51] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.002 0.004
2025-09-27 14:41:51,667 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:51] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.016 0.015
2025-09-27 14:41:51,717 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:51] "POST /mail/thread/messages HTTP/1.1" 200 - 18 0.038 0.026
2025-09-27 14:41:53,322 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:53] "POST /web/dataset/call_kw/customer.map/web_read HTTP/1.1" 200 - 2 0.001 0.003
2025-09-27 14:41:53,661 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:53] "POST /mail/thread/data HTTP/1.1" 200 - 10 0.004 0.008
2025-09-27 14:41:53,684 6268 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [27/Sep/2025 14:41:53] "POST /mail/thread/messages HTTP/1.1" 200 - 18 0.008 0.010
2025-09-27 14:42:03,950 6268 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-27 14:42:03,952 6268 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-27 14:42:05,051 6268 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 5 connections  
2025-09-28 00:22:02,805 19780 INFO ? odoo: Odoo version 17.0 
2025-09-28 00:22:02,817 19780 INFO ? odoo: Using configuration file at D:\work-project\ssi\odoo_demo\odoo\odoo.conf 
2025-09-28 00:22:02,818 19780 INFO ? odoo: addons paths: ['D:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\data\\addons\\17.0', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\field_service', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\custom_addons\\geospatial', 'd:\\work-project\\ssi\\odoo_demo\\odoo\\odoo\\addons'] 
2025-09-28 00:22:02,818 19780 INFO ? odoo: database: odoo@localhost:5432 
2025-09-28 00:22:03,075 19780 INFO ? odoo.addons.base.models.ir_actions_report: Will use the Wkhtmltopdf binary at C:\Program Files\wkhtmltopdf\bin\wkhtmltopdf.exe 
2025-09-28 00:22:03,465 19780 WARNING ? odoo.service.server: 'watchdog' module not installed. Code autoreload feature is disabled 
2025-09-28 00:22:03,465 19780 INFO ? odoo.service.server: HTTP service (werkzeug) running on LAPTOP-O0EP5QSP:8069 
2025-09-28 00:22:03,505 19780 INFO ssi_odoo_demo odoo.modules.loading: loading 1 modules... 
2025-09-28 00:22:03,513 19780 INFO ssi_odoo_demo odoo.modules.loading: 1 modules loaded in 0.01s, 0 queries (+0 extra) 
2025-09-28 00:22:03,533 19780 INFO ssi_odoo_demo odoo.modules.loading: updating modules list 
2025-09-28 00:22:03,534 19780 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on [] to user __system__ #1 via n/a 
2025-09-28 00:22:04,655 19780 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'product_master', defaulting to LGPL-3 
2025-09-28 00:22:04,805 19780 WARNING ssi_odoo_demo odoo.modules.module: Missing `license` key in manifest for 'stock_qr_tracking', defaulting to LGPL-3 
2025-09-28 00:22:05,152 19780 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_upgrade on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-28 00:22:05,153 19780 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.update_list on ['Customer Map Tracking'] to user __system__ #1 via n/a 
2025-09-28 00:22:05,740 19780 INFO ssi_odoo_demo odoo.addons.base.models.ir_module: ALLOW access to module.button_install on [] to user __system__ #1 via n/a 
2025-09-28 00:22:05,772 19780 INFO ssi_odoo_demo odoo.modules.loading: loading 77 modules... 
2025-09-28 00:22:06,303 19780 INFO ssi_odoo_demo odoo.modules.loading: Loading module customer_map_tracking (28/77) 
2025-09-28 00:22:06,355 19780 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.customer_map_tracking.models.customer_map is not overriding the create method in batch 
2025-09-28 00:22:06,391 19780 INFO ssi_odoo_demo odoo.modules.registry: module customer_map_tracking: creating or updating database tables 
2025-09-28 00:22:06,473 19780 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/security.xml 
2025-09-28 00:22:06,554 19780 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/security/ir.model.access.csv 
2025-09-28 00:22:06,571 19780 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_views.xml 
2025-09-28 00:22:06,598 19780 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_geoengine_views.xml 
2025-09-28 00:22:06,624 19780 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_actions.xml 
2025-09-28 00:22:06,631 19780 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/views/customer_map_menus.xml 
2025-09-28 00:22:06,651 19780 INFO ssi_odoo_demo odoo.modules.loading: loading customer_map_tracking/demo/customer_map_demo.xml 
2025-09-28 00:22:07,031 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded 
2025-09-28 00:22:07,031 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:07,417 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:07,417 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:07,806 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:07,806 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:08,182 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:08,182 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:08,527 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:08,527 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:08,857 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:08,857 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:09,261 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:09,261 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:09,640 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:09,640 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:09,909 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:09,909 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:10,305 19780 ERROR ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Failed to create PostGIS geometry: maximum recursion depth exceeded while calling a Python object 
2025-09-28 00:22:10,305 19780 WARNING ssi_odoo_demo odoo.addons.customer_map_tracking.models.customer_map: Could not sync coordinates to PostGIS: Failed to create PostGIS geometry. Please check your PostGIS installation. 
2025-09-28 00:22:10,373 19780 INFO ssi_odoo_demo odoo.modules.loading: Module customer_map_tracking loaded in 4.07s, 5129 queries (+5129 other) 
2025-09-28 00:22:11,028 19780 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.product_master.models.product_template is not overriding the create method in batch 
2025-09-28 00:22:11,041 19780 WARNING ssi_odoo_demo odoo.api.create: The model odoo.addons.purchase_fsm_assignment_api.models.installation_checklist is not overriding the create method in batch 
2025-09-28 00:22:11,088 19780 INFO ssi_odoo_demo odoo.modules.loading: 77 modules loaded in 5.32s, 5129 queries (+5129 extra) 
2025-09-28 00:22:11,295 19780 WARNING ssi_odoo_demo py.warnings: D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py:536: UserWarning: Property fsm.size.name.required should be a boolean (True).
  File "D:\work-project\ssi\odoo_demo\odoo\odoo-bin", line 8, in <module>
    odoo.cli.main()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\command.py", line 67, in main
    o.run(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 186, in run
    main(args)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\cli\server.py", line 179, in main
    rc = odoo.service.server.start(preload=preload, stop=stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1469, in start
    rc = server.run(preload, stop)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 635, in run
    rc = preload_registries(preload)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\service\server.py", line 1369, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\loading.py", line 493, in load_modules
    registry.setup_models(cr)
  File "D:\work-project\ssi\odoo_demo\odoo\venv\Lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\tools\func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\modules\registry.py", line 319, in setup_models
    model._setup_fields()
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\models.py", line 3420, in _setup_fields
    field.setup(self)
  File "D:\work-project\ssi\odoo_demo\odoo\odoo\fields.py", line 536, in setup
    warnings.warn(f'Property {self}.required should be a boolean ({self.required}).')
 
2025-09-28 00:22:11,683 19780 INFO ssi_odoo_demo odoo.modules.registry: verifying fields for every extended model 
2025-09-28 00:22:12,280 19780 INFO ssi_odoo_demo odoo.modules.loading: Modules loaded. 
2025-09-28 00:22:12,301 19780 INFO ssi_odoo_demo odoo.modules.registry: Registry loaded in 8.836s 
2025-09-28 00:22:15,491 19780 INFO ssi_odoo_demo odoo.addons.base.models.ir_http: Generating routing map for key None 
2025-09-28 00:22:15,514 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:15] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 7 0.005 0.094
2025-09-28 00:22:15,697 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:15] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 10 0.004 0.010
2025-09-28 00:22:15,850 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:15] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 12 0.008 0.009
2025-09-28 00:22:16,053 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:16] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.001 0.008
2025-09-28 00:22:17,668 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:17] "GET /websocket?version=17.0-1 HTTP/1.1" 101 - 1 0.001 0.006
2025-09-28 00:22:18,005 19780 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres 
2025-09-28 00:22:19,808 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:19] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.001 0.004
2025-09-28 00:22:27,705 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:27] "POST /web/dataset/call_kw/customer.map/web_search_read HTTP/1.1" 200 - 2 0.000 0.010
2025-09-28 00:22:27,978 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:27] "POST /web/dataset/call_kw/geoengine.vector.layer/web_search_read HTTP/1.1" 200 - 8 0.008 0.010
2025-09-28 00:22:28,055 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:28] "POST /web/dataset/call_kw/customer.map/get_geoengine_layers HTTP/1.1" 200 - 11 0.009 0.010
2025-09-28 00:22:28,312 19780 INFO ssi_odoo_demo werkzeug: 127.0.0.1 - - [28/Sep/2025 00:22:28] "POST /web/dataset/call_kw/ir.model/display_name_for HTTP/1.1" 200 - 3 0.003 0.007
2025-09-28 00:22:33,601 19780 INFO ssi_odoo_demo odoo.service.server: Initiating shutdown 
2025-09-28 00:22:33,601 19780 INFO ssi_odoo_demo odoo.service.server: Hit CTRL-C again or send a second signal to force the shutdown. 
2025-09-28 00:22:34,641 19780 INFO ssi_odoo_demo odoo.sql_db: ConnectionPool(used=0/count=0/max=64): Closed 3 connections  
